Fix compilation on Alpine:3.7
The fix for c_src/gen_socket_nif.c includes 'errno.h' (insteadof 'sys/errno.h')
which is part of the standard C library.

```
cc -Wall -Werror -fPIC -I. -I/usr/lib/erlang/lib/erl_interface-3.10/include
  -I/usr/lib/erlang/erts-9.1.5/include
  -c -o gen_socket_nif.o gen_socket_nif.c
In file included from gen_socket_nif.c:59:0:
/usr/include/sys/errno.h:1:2: error: #warning redirecting incorrect
 #include <sys/errno.h> to <errno.h> [-Werror=cpp]

 #warning redirecting incorrect #include <sys/errno.h> to <errno.h>
  ^~~~~~~
cc1: all warnings being treated as errors
```

The fix for c_src/gen_socket_drv.c just removes the apparently unused
'error.h' header which was not available anyway on Alpine Linux:

```
cc -Wall -Werror -fPIC -I. -I/usr/lib/erlang/lib/erl_interface-3.10/include
  -I/usr/lib/erlang/erts-9.1.5/include
  -c -o gen_socket_drv.o gen_socket_drv.c
gen_socket_drv.c:41:19: fatal error: error.h: No such file or directory
 #include <error.h>
```